[package]
name = "stark_safari"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.10.1" }
starknet = "2.3.0"

[[target.starknet-contract]]
casm = true

[tool.sncast.safaristark]
account = "safaristark"
accounts-file = "/home/ted/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-goerli.infura.io/v3/7d48ff9fbf924034a5ecebd836f4ff6f"

[tool.sncast.stark]
account = "stark"
accounts-file = "/home/ted/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-mainnet.infura.io/v3/bc68aac3cb0747fbb09971ae6c2947df"

[tool.sncast.starknet]
account = "starknet"
accounts-file = "/home/ted/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-mainnet.infura.io/v3/bc68aac3cb0747fbb09971ae6c2947df"

[tool.sncast.ted]
account = "ted"
accounts-file = "/home/ted/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-mainnet.infura.io/v3/bc68aac3cb0747fbb09971ae6c2947df"

[tool.sncast.adams]
account = "adams"
accounts-file = "/home/ted/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-mainnet.infura.io/v3/bc68aac3cb0747fbb09971ae6c2947df"
